app = "bad-web-app"  # Replace with your Fly.io app name

primary_region = "ams"  # Replace with your preferred Fly region

[build]
  dockerfile = "Dockerfile"

[env]
  FLASK_ENV = "production"
  PORT = "5000"

[[mounts]]
  source = "app_data"
  destination = "/app/instances"

[http_service]
  internal_port = 5000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
